### ISSUE TITLE
What is the license? 

### ISSUE THREAD

**Issue by Inscure** [WebChemistry/svg-pdf#1]
Hello,

We would like to use your library in our project, but we couldn't find the license information. The repository doesn't contain a LICENSE file.

Could you please add a LICENSE file? We would greatly appreciate it.

**Comment by Inscure** [comment]
@MartkCz  If we may suggest a specific license, the MIT or BSD License would offer the greatest flexibility.

**Comment by Inscure** [comment]
@MartkCz, could I please ask you to add a new tag and update packagist.org? Thank you!

**Comment by MartkCz** [comment]
https://github.com/WebChemistry/svg-pdf/releases/tag/v1.1.4
